### ISSUE TITLE
Make sure WBS 1.1.10-1.1.15 print after 1.1.9

### ISSUE THREAD

**Issue by daniel-r-germony** [daniel-r-germony/dstCSDR#18]
Carolin noted that they did not in the initial version of the 1921 pivot wider.

This may be OBE based on recoding of the 1921-1 files but is a good reminder to check that WBS always print the way a user would expect.

**Comment by ahjames11** [comment]
Suggest creating a function called `wbs_sort()` for this. Might want to make it pipeable.

Other naming option perhaps `arrange_wbs()` to borrow from the `dplyr` verb. This would require non-standard evaluation.

```r
report_df %>%
  arrange_wbs(wbs_field)
```

A potentially more advanced method would be to create a WBS data-type and then add a generic for it.

`as_wbs(vector)` -> gives it of class WBS

Then you could add a generic for some of the `dplyr` verbs.

I am also tempted to split this into a package of its own called `wbstools` or something.
